version: '3'
services:
  myproxy:
    image: nginx:1.18.0
    ports:
      - "50443:443"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/ssl:/opt/ssl
      - ./proxy/logs:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      mynet:
        ipv4_address: 172.31.0.2

networks:
  mynet:
    external:
      name: testnet
